Shimmy Shimmy Bank/Shimmy.shimmy.bank/website/__init__.py
from flask import Flask
def create_app():
    app=Flask(__name__,template_folder='templates', static_folder='static')
    app.config['SECRET_KEY'] = '12345'
    from .views import views
    from .auth import auth
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    return app

Shimmy Shimmy Bank/Shimmy.shimmy.bank/website/auth.py
from flask import Blueprint, render_template, jsonify, request, url_for, redirect, session
from website.functions import *
import mysql.connector as sqltor
import time
c=r=0
l_user={};user={}
auth=Blueprint('auth', __name__)
mycon=sqltor.connect(host='localhost',user='root1',password='12345',database='shimmy_shimmy_bank',autocommit=True)
cursor=mycon.cursor()

@auth.route('/login',methods=['GET'])
def login():
    return render_template('login.html')
       
@auth.route('/login_btn',methods=['POST'])
def login_btn():
    l_user['cid'],l_user['password']=request.form['l_cid'],request.form['l_password']
    s_sql()
    if check_login(l_user):
        s=get_info_login(l_user)
        session['user']=s
        session['login']=True
        return redirect(url_for('views.home'))
    else:
        session['l_fail']=True
        return redirect(url_for('auth.login'))

@auth.route('/update_btn',methods=['POST'])
def update_btn():
    l_user['aadhaar'],l_user['password'],l_user['name']=request.form['l_aadhaar'],request.form['l_password'],request.form['name']
    print(session['user']['cid'])
    print(l_user)
    if l_user['aadhaar']:
        cursor.execute('update users set aadhar="%s" where cid="%s"'%(l_user['aadhaar'],session['user']['cid']))
    if l_user['password']:
        cursor.execute('update users set password="%s" where cid="%s"'%(l_user['password'],session['user']['cid']))
    if l_user['name']:
        cursor.execute('update users set name="%s" where cid="%s"'%(l_user['name'],session['user']['cid']))
    session['update']=True
    return redirect(url_for('auth.update'))

@auth.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')

@auth.route('/signup_btn',methods=['POST'])
def signup_btn():
    user['cid']=str(randint(100000,999999))
    user['name'],user['email']=request.form['name'],str(request.form['email'])
    user['password'],user['aadhaar'],user['age']=request.form['password'],request.form['aadhaar'],request.form['age']
    # user - cid, name, email, password, aadhaar, age
    return redirect(url_for('auth.verify'))


@auth.route('/verify', methods=['GET'])
def verify():
        global r
        global c
        if not c:
            r=send_mail_ver(user['email'])
            c+=1
        return render_template('verify.html')

@auth.route('/verify_btn',methods=['POST'])
def verify_btn():
    o=int(request.form['otp'])
    if o==r:
        s_sql()
        add_user_sql(user)
        send_mail_acc(user)
        user['sb']=-1
        session['user']=user
        session['login']=True
        session['user']['sb']=randint(10000,99999)
        session.modified=True
        add_sb(session['user'])
        send_mail_sb(session['user'])
        return redirect(url_for('views.home'))
    else:
        session['v_fail']=True
        return redirect(url_for('auth.verify'))

@auth.route('/logout')
def logout():
    c_sql()
    session.pop('user', None)
    return redirect(url_for('views.home'))   

@auth.route('/update')
def update():
    return render_template('update.html')

Shimmy Shimmy Bank/Shimmy.shimmy.bank/website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from website.functions import *
from random import randint
from datetime import date
views = Blueprint('views', __name__)

@views.route('/', methods=['GET'])
def home():
    return render_template('index.html')

@views.route('/ourservices', methods=['GET'])
def ourservices():
    return render_template('ourservices.html') 


@views.route('/profile')
def profile():
    session["user"]["sb_b"]=get_sb_b(session['user'])
    return render_template('profile.html',user=session['user'])


@views.route('/transhistsav',methods=['GET'])
def transhistsav():
    l=get_t_sb(session['user'])
    #date amount particular balance tid
    return render_template('transhistsav.html',lasvegas=l)

@views.route('/carloan',methods=['GET'])
def carloan():
    return render_template('carloan.html')

@views.route('carloan_btn',methods=['POST'])
def carloan_btn():
    interest={3:5,6:5.5,12:12,24:14,60:17,120:20,240:24}
    amt=int(request.form['loan_amt'])
    form_tp=int(request.form.get('time_period'))
    tp=date.today()+relativedelta(months=form_tp)
    c_loan_details={'amt':amt,'tp':form_tp,'interest':interest[form_tp]}
    session['user']['c_loan']=c_loan_details
    add_c_loan(session['user'])
    send_mail_c_loan(session['user'])
    return redirect(url_for('views.carloan'))


@views.route('/homeloan',methods=['GET'])
def homeloan():
    return render_template('homeloan.html')

@views.route('/homeloan_btn',methods=['POST'])
def homeloan_btn():
    interest={3:5,6:5.5,12:12,24:14,60:17,120:20,240:24}
    amt=int(request.form['loan_amt'])
    form_tp=int(request.form.get('time_period'))
    print(form_tp, type(form_tp))
    tp=date.today()+relativedelta(months=form_tp)
    h_loan_details={'amt':amt,'tp':form_tp,'interest':interest[form_tp]}
    session['user']['h_loan']=h_loan_details
    add_h_loan(session['user'])
    send_mail_h_loan(session['user'])
    return redirect(url_for('views.homeloan'))

@views.route('/transfer',methods=['GET'])
def transfer():
    return render_template('transfer.html')

@views.route('/s_transfer_btn',methods=['POST'])
def s_transfer_btn():
    s_amt=int(request.form['s_transfer_amt'])
    s_no=request.form['s_no']
    # reciever amt user
    t=sb_t(s_no,s_amt,session['user'])
    if t:
        send_mail_d(get_reciever_id(s_no),s_amt)
        send_mail_w(session['user'],s_amt)
    return redirect(url_for('views.transfer'))


@views.route('/withdraw',methods=['GET'])
def withdraw():
    return render_template('withdraw.html')

@views.route('/withdraw_btn',methods=['POST'])
def withdraw_btn():
    amt=int(request.form['amt'])
    if withdraw_(session['user'],amt):
        send_mail_w(session['user'],amt)
    return redirect(url_for('views.withdraw'))

@views.route('/deposit',methods=['GET'])
def deposit():
    return render_template('deposit.html')

@views.route('/deposit_btn',methods=['POST'])
def deposit_btn():
    amt=request.form['amt']
    deposit_(session['user'],amt)
    send_mail_d(session['user'],amt)
    return redirect(url_for('views.deposit'))

@views.route('hl_t_btn',methods=['POST'])
def hl_t_btn():
    h_loan_transfer(session['user'])
    session['h_loan_transfer']=True
    print(session['user']['h_loan']['amt'])
    send_mail_d(session['user'],session['user']['h_loan']['amt'])
    return redirect(url_for('views.homeloan'))

@views.route('cl_t_btn',methods=['POST'])
def cl_t_btn():
    c_loan_transfer(session['user'])
    session['c_loan_transfer']=True
    send_mail_d(session['user'],session['user']['c_loan']['amt'])
    return redirect(url_for('views.carloan'))

Shimmy Shimmy Bank/Shimmy.shimmy.bank/website/templates/carloan.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block scripts %}<link rel="stylesheet" type="text/css" href="../static/styles/homeloan.css">{{ super() }}
  <title>Apply for a Car Loan</title>
</head>
<body style="background-color: #a0d5df;">
  <!-- Navbar -->
  {% block navbar %}
    {{ super() }}
  {% endblock %}
  <!-- Content -->
  <div class="col-sm-8">
    <div class="summary flex">
      <h1 style="font-family: 'Courier New'"><center><b>CAR LOAN</b></center></h1>
    </div>
  </div>
  <br><br><br>
  <div class="card">
    <div class="card-body">
          <div>
            <h1 style="font-family: 'Courier New'"><center><b>APPLY FOR A CAR LOAN</b></center></h1>
            <h2 style="font-family: 'Courier New'"><center><b>Prerequisites:</b></center></h2>
            <ul style="font-family: 'Courier New'">
              <li><b>Age:</b> <b>You must be at least 18 years old.</b></li>
              <li><b>Income:</b> <b>You must have a stable source of income.</b></li>
              <li><b>Accounts:</b> <b><u>You must have a savings account under our bank.</u></b></li>
              <li><b>Credit Score:</b> <b>A good credit score is essential.</b></li>
              <li><b>Vehicle Documents:</b> <b>You must have the necessary vehicle documents ready.</b></li>
            </ul>
            <h3 style="font-family: 'Courier New'"><center><b>Interest rates and time periods are as follows:</b></center></h3>
            <ul style="font-family: 'Courier New'">
              <li><b>3 months:</b> 5% per annum</li>
              <li><b>6 months:</b> 5.5% per annum</li>
              <li><b>12 months (1 year):</b> 12% per annum</li>
              <li><b>24 months (2 years):</b> 14% per annum</li>
              <li><b>60 months (5 years):</b> 17% per annum</li>
              <li><b>120 months (10 years):</b> 20% per annum</li>
              <li><b>240 months (20 years):</b> 24% per annum</li>
            </ul>
              <center><details><summary style="font-family: 'Courier New'"><b>Enter amount and choose time period</b></summary>
              <form method="post" action="{{ url_for('views.carloan_btn') }}">
              <fieldset>
                  <center><div class="form-group">
                  <label for="Amount" style="color: #4f5769;"><b>Enter Amount:</b></label>
                  <input type="number" min="1" max="150000000" class="form-control" id="Amount" placeholder="Enter Amount" name="loan_amt" required>
                </div></center>
              <ul>
                <li>
                  <label for="3months"><font style="font-family: 'Courier New'">3 months</font><input type="radio" id="3months" name="time_period" value="3" /></label>

                </li>
                <li>
                  <label for="6months"><font style="font-family: 'Courier New'">6 months</font><input type="radio" id="6months" name="time_period" value="6" /></label>
                </li>
               <li>
                 <label for="1year"><font style="font-family: 'Courier New'">1 year</font><input type="radio" id="1year" name="time_period" value="12" /></label>
                </li>
                <li>
                 <label for="2years"><font style="font-family: 'Courier New'">2 years</font><input type="radio" id="2years" name="time_period" value="24" /></label>
                </li>
                <li>
                 <label for="5years"><font style="font-family: 'Courier New'">5 years</font><input type="radio" id="5years" name="time_period" value="60" /></label>
                </li>
                <li>
                 <label for="10years"><font style="font-family: 'Courier New'">10 years</font><input type="radio" id="10years" name="time_period" value="120" /></label>
                </li>
                <li>
                 <label for="20years"><font style="font-family: 'Courier New'">20 years</font><input type="radio" id="20years" name="time_period" value="240" /></label>
                </li>
                <br><center><button type="submit" class="btn btn-info" @click="submitForm"><b><a style="text-decoration: none;color: white;">Confirm Car loan application</a></b></button></center>
             </ul>
            </fieldset>
         </form>
        </details></center><br><br>
        {% if session.get('c_loan')==True %}
          <dialog open style="width: 95%; height: 110px; top: 555px; left: 0; border: 2px solid rgb(0, 0, 0); border-radius: 12px;; background-color: rgb(148, 201, 146); box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
            <form method="dialog" open>
              <center> <button class="Close-button" aria-label="Close" style="background-color: rgb(157, 194, 141); border-radius: 12px; color: rgb(255, 255, 255); cursor: pointer;"><b>Close</b></button></center>
              <center><p style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color: rgb(0, 0, 0);font-size: 20px; padding-left: 20px;"><b>Car loan application successful</b></p></center>
            </form>
            {% if session.user['sb']!=-1 %}
              <form method="post" action="{{ url_for('views.cl_t_btn') }}">
                  <br><center><button type="submit" style="background-color: #4c98af; height: 100%; width: 100%; cursor: pointer; color: white"><b>Transfer loan amount to savings bank account</b></button></center>
              </form>
            {% endif %}
          </dialog>
          {% set dummy=session.pop('c_loan') %}
        {% endif %}
        {% if session.get('c_loan_transfer')==True %}
          <dialog open style="width: 95%; height: 110px; top: 555px; left: 0; border: 2px solid rgb(0, 0, 0); border-radius: 12px;; background-color: rgb(148, 201, 146); box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
            <form method="dialog" open>
              <center> <button class="Close-button" aria-label="Close" style="background-color: rgb(157, 194, 141); border-radius: 12px; color: rgb(255, 255, 255); cursor: pointer;"><b>Close</b></button></center>
              <center><p style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color: rgb(0, 0, 0);font-size: 20px;padding-left: 10px;"><b>Loan amount transferred to savings bank account successfully</b></p></center>
            </form>
          {% set dummy=session.pop('c_loan_transfer') %}
        {% endif %}
          </div>
        </div>
      </div>
    <br><br><br><br>
{% endblock %}

<!-- Footer -->
{% block footer %}{{ super() }}{% endblock %}
</body>
</html>

Shimmy Shimmy Bank/Shimmy.shimmy.bank/website/templates/deposit.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block scripts %}<link rel="stylesheet" type="text/css" href="../static/styles/transfer.css">{{ super() }}
  <title>Deposit to account</title>
</head>
<body style="background-color: #a0d5df;">
  {% endblock %}
  <!-- Navbar -->
  {% block navbar %}
    {{ super() }}
  <!-- Content -->
  <br><br><br>
  <div class="card">
    <div class="card-body">
          <div>
            <h1 style="font-family: 'Courier New'"><center><b>DEPOSIT INTO ACCOUNT</b></center></h1>
            <center><h3 style="font-family: 'Courier New'"><b>Maximum Amount : 150000000</b></h3></center>
            <form method="post" action="{{ url_for('views.deposit_btn') }}">
                <center><div class="form-group">
                  <label for="amount" style="color: #4f5769;"><b>Enter amount:</b></label>
                  <input type="number" min="1" max="150000000" class="form-control" id="amount" placeholder="Enter amount" required name="amt">
                </div></center>
                {% block submit %}<center><button type="submit" class="btn btn-info" @click="submitForm"><b><a style="text-decoration: none;color: white;">Confirm Transfer</a></b></button></center>{% endblock %}
                <center><button type="submit" class="btn btn-info" @click="submitForm"><b><a href="{{ url_for('views.ourservices') }}" style="text-decoration: none;color: white;">Go back to services</a></b></button></center>
            </form>
            {% if session.get('deposit_')==True %}
              <dialog open style="width: 95%; height: 90px; top: 210px; left: 0; border: 2px solid rgb(0, 0, 0); border-radius: 12px;; background-color: rgb(148, 201, 146); box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
                <form method="dialog" open>
                  <center> <button class="Close-button" aria-label="Close" style="background-color: rgb(157, 194, 141); border-radius: 12px; color: rgb(255, 255, 255); cursor: pointer;"><b>Close</b></button></center>
                  <center><p style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color: rgb(0, 0, 0);font-size: 20px;"><b>Deposit successful!!</b></p></center>
              </dialog>
              {% set dummy=session.pop('deposit_') %}
            {% endif %}
          </div>
          </div>
        </div>
      </div>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  {% endblock %}
<!-- Footer -->
{% block footer %}{{ super() }}{% endblock %}
</body>
</html>

Shimmy Shimmy Bank/Shimmy.shimmy.bank/website/templates/homeloan.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block scripts %}<link rel="stylesheet" type="text/css" href="../static/styles/homeloan.css">{{ super() }}
  <title>Apply for a Home Loan</title>
</head>
<body style="background-color: #a0d5df;">
  {% endblock %}
  <!-- Navbar -->
  {% block navbar %}
    {{ super() }}
  
  <!-- Content -->
  <div class="col-sm-8">
    <div class="summary flex">
      <h1 style="font-family: 'Courier New'"><center><b>HOME LOAN</b></center></h1>
    </div>
  </div>
  <br><br><br>
  <div class="card">
    <div class="card-body">
          <div>
            <h1 style="font-family: 'Courier New'"><center><b>APPLY FOR A HOME LOAN</b></center></h1>
            <h2 style="font-family: 'Courier New'"><center><b>Prerequisites:</b></center></h2>
            <ul style="font-family: 'Courier New'">
              <li><b>Age:</b> <b>You must be at least 18 years old.</b></li>
              <li><b>Income:</b> <b>You must have a stable source of income.</b></li>
              <li><b>Accounts:</b> <b><u>You must have a savings account under our bank.</u></b></li>
              <li><b>Credit Score:</b> <b>A good credit score is essential.</b></li>
              <li><b>Property Documents:</b> <b>You must have the necessary property documents ready.</b></li>
            </ul>
            <h3 style="font-family: 'Courier New'"><center><b>Interest rates are as follows:</b></center></h3>
            <ul style="font-family: 'Courier New'">
              <li><b>3 months:</b> 5% per annum</li>
              <li><b>6 months:</b> 5.5% per annum</li>
              <li><b>1 year:</b> 12% per annum</li>
              <li><b>2 years:</b> 14% per annum</li>
              <li><b>5 years:</b> 17% per annum</li>
              <li><b>10 years:</b> 20% per annum</li>
              <li><b>20 years:</b> 24% per annum</li>
            </ul>
          <center><details><summary style="font-family: 'Courier New'"><b>Enter amount and choose time period</b></summary>
              <form method="post" action="{{ url_for('views.homeloan_btn') }}">
              <fieldset>
                  <center><div class="form-group">
                  <label for="Amount" style="color: #4f5769;"><b>Enter Amount:</b></label>
                  <input name="loan_amt" type="number" min="1" max="150000000" class="form-control" id="Amount" placeholder="Enter Amount" required>
                  </div></center>
              <ul>
                <li>
                  <label for="3months"><font style="font-family: 'Courier New'">3 months</font><input type="radio" id="3months" name="time_period" value="3" /></label>

                </li>
                <li>
                  <label for="6months"><font style="font-family: 'Courier New'">6 months</font><input type="radio" id="6months" name="time_period" value="6" /></label>
                </li>
               <li>
                 <label for="1year"><font style="font-family: 'Courier New'">1 year</font><input type="radio" id="1year" name="time_period" value="12" /></label>
                </li>
                <li>
                 <label for="2years"><font style="font-family: 'Courier New'">2 years</font><input type="radio" id="2years" name="time_period" value="24" /></label>
                </li>
                <li>
                 <label for="5years"><font style="font-family: 'Courier New'">5 years</font><input type="radio" id="5years" name="time_period" value="60" /></label>
                </li>
                <li>
                 <label for="10years"><font style="font-family: 'Courier New'">10 years</font><input type="radio" id="10years" name="time_period" value="120" /></label>
                </li>
                <li>
                 <label for="20years"><font style="font-family: 'Courier New'">20 years</font><input type="radio" id="20years" name="time_period" value="240" /></label>
                </li>
                <br><center><button type="submit" class="btn btn-info" @click="submitForm"><b><a style="text-decoration: none;color: white;">Confirm Home loan application</a></b></button></center>
             </ul>
            </fieldset>
         </form>
        </details></center><br><br>
    {% if session.get('h_loan')==True %}
      <dialog open style="width: 95%; height: 110px; top: 520px; left: 0; border: 2px solid rgb(0, 0, 0); border-radius: 12px;; background-color: rgb(148, 201, 146); box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
        <form method="dialog" open>
          <center> <button class="Close-button" aria-label="Close" style="background-color: rgb(157, 194, 141); border-radius: 12px; color: rgb(255, 255, 255); cursor: pointer;"><b>Close</b></button></center>
          <center><p style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color: rgb(0, 0, 0);font-size: 20px; padding-left: 20px;"><b>Home loan application successful</b></p></center>
        </form>
        {% if session.user['sb']!=-1 %}
          <form method="post" action="{{ url_for('views.hl_t_btn') }}">
             <br><center><button type="submit" style="background-color: #4c98af; height: 100%; width: 100%; cursor: pointer; color: white"><b>Transfer loan amount to savings bank account</b></button></center>
          </form>
        {% endif %}
        <br>
      </dialog>
      {% set dummy=session.pop('h_loan') %}
    {% endif %}
    {% if session.get('h_loan_transfer')==True %}
      <dialog open style="width: 95%; height: 110px; top: 520px; left: 0; border: 2px solid rgb(0, 0, 0); border-radius: 12px;; background-color: rgb(148, 201, 146); box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
        <form method="dialog" open>
          <center> <button class="Close-button" aria-label="Close" style="background-color: rgb(157, 194, 141); border-radius: 12px; color: rgb(255, 255, 255); cursor: pointer;"><b>Close</b></button></center>
          <center><p style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color: rgb(0, 0, 0);font-size: 20px;padding-left: 10px;"><b>Loan amount transferred to savings bank account successfully</b></p></center>
        </form>
      {% set dummy=session.pop('h_loan_transfer') %}
    {% endif %}
      <br>
      </dialog>
          </div>
        </div>
      </div>
    <br><br><br><br>
  {% endblock %}
<!-- Footer -->
{% block footer %}{{ super() }}{% endblock %}

</body>
</html>

Shimmy Shimmy Bank/Shimmy.shimmy.bank/website/templates/transfer.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block scripts %}<link rel="stylesheet" type="text/css" href="../static/styles/transfer.css">{{ super() }}
  <title>Transfer from Savings account</title>
</head>
<body style="background-color: #a0d5df;">
  {% endblock %}
  <!-- Navbar -->
  {% block navbar %}
    {{ super() }}
  <!-- Content -->
  <br><br><br>
  <div class="card">
    <div class="card-body">
          <div>
            <h1 style="font-family: 'Courier New'"><center><b>{% block trans %}TRANSFER FROM SAVINGS ACCOUNT{% endblock %}</b></center></h1>
            <center><h3 style="font-family: 'Courier New'"><b>Maximum Amount : 150000000</b></h3></center>
            <form method="post" action="{{ url_for('views.s_transfer_btn') }}">
                <center><div class="form-group">
                  <label for="amount" style="color: #4f5769;"><b>{% block amount %}Enter amount:{% endblock %}</b></label>
                  <input type="number" max="150000000" min="1" class="form-control" id="amount" placeholder="Enter amount" required name="s_transfer_amt">
                </div></center>
                <center><div class="form-group">
                  <label for="recipientAccount" style="color: #4f5769;"><b>{% block recep %}Enter recipient's bank savings bank account number :{% endblock %}</b></label>
                  <input type="text" maxlength="5" class="form-control" id="recipientAccount" placeholder="Enter recipient's Savings bank number" name="s_no" required>
                </div></center> 
                {% block submit %}<center><button type="submit" class="btn btn-info" @click="submitForm"><b><a style="text-decoration: none;color: white;">Confirm Transfer</a></b></button></center>{% endblock %}
                <center><button type="submit" class="btn btn-info" @click="submitForm"><b><a href="{{ url_for('views.ourservices') }}" style="text-decoration: none;color: white;">Go back to services</a></b></button></center>
            </form>

          {% if session.get('s_transfer')==True %}
            <dialog open style="width: 95%; height: 90px; top: 343px; left: 0; border: 2px solid rgb(0, 0, 0); border-radius: 12px;; background-color: rgb(148, 201, 146); box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
              <form method="dialog" open>
                <center> <button class="Close-button" aria-label="Close" style="background-color: rgb(157, 194, 141); border-radius: 12px; color: rgb(255, 255, 255); cursor: pointer;"><b>Close</b></button></center>
                <center><p style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color: rgb(0, 0, 0);font-size: 20px;"><b>Transfer successful!!</b></p></center>
            </dialog>
            {% set dummy=session.pop('s_transfer') %}
          {% endif %}

          {% if session.get('t_user_not_found')==True %}
            <dialog open style="width: 95%; height: 90px; top: 343px; left: 0; border: 2px solid rgb(0, 0, 0); border-radius: 12px;; background-color: rgb(243, 95, 95); box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
              <form method="dialog" open>
                <center> <button class="Close-button" aria-label="Close" style="background-color: rgb(157, 194, 141); border-radius: 12px; color: rgb(255, 255, 255); cursor: pointer;"><b>Close</b></button></center>
                <center><p style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color: rgb(0, 0, 0);font-size: 20px;"><b>Recipient not found. Please try again.</b></p></center>
            </dialog>
            {% set dummy=session.pop('t_user_not_found') %}
          {% endif %}
          {% if session.get('insufficient_funds')==True %}
            <dialog open style="width: 95%; height: 90px; top: 343px; left: 0; border: 2px solid rgb(0, 0, 0); border-radius: 12px;; background-color: rgb(243, 95, 95); box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
              <form method="dialog" open>
                <center> <button class="Close-button" aria-label="Close" style="background-color: rgb(157, 194, 141); border-radius: 12px; color: rgb(255, 255, 255); cursor: pointer;"><b>Close</b></button></center>
                <center><p style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color: rgb(0, 0, 0);font-size: 20px;"><b>Insufficient funds. Please try again.</b></p></center>
            </dialog>
            {% set dummy=session.pop('insufficient_funds') %}
          {% endif %}
            <br>
          </div>
          </div>
        </div>
      </div>
  <br><br><br><br><br><br><br><br><br><br><br><br><br>
  {% endblock %}
<!-- Footer -->
{% block footer %}{{ super() }}{% endblock %}
</body>
</html>